columnlines <- c("black", "red", "blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
plot(datatouse$SetTime, datatouse$Sub_metering_1, type="l", col=columnlines[1], xlab="", ylab="Energy sub metering")
lines(datatouse$SetTime, datatouse$Sub_metering_2, col=columnlines[2])
lines(datatouse$SetTime, datatouse$Sub_metering_3, col=columnlines[3])
legend("topright", legend=labels, col=columnlines, lty="solid")
